/*
     Title: Constant for ASSIGN_INPUT_TABLE
     Description: Constant for ASSIGN_INPUT_TABLE
     Author: Iqbal Hossain
     Date: 26-January-2022
     Modified: 26-January-2022
*/

export const FETCH_ASSIGN_INPUT_TABLE = 'FETCH_ASSIGN_INPUT_TABLE';
export const FETCH_ASSIGN_INPUT_TABLE_BY_QUERY = 'FETCH_ASSIGN_INPUT_TABLE_BY_QUERY';
export const FETCH_ASSIGN_INPUT_TABLE_BY_ID = 'FETCH_ASSIGN_INPUT_TABLE_BY_ID';
export const FETCH_ASSIGN_INPUT_TABLE_BY_RANGE = 'FETCH_ASSIGN_INPUT_TABLE_BY_RANGE';
export const FETCH_ASSIGN_INPUT_FOR_PENDING = 'FETCH_ASSIGN_INPUT_FOR_PENDING';
export const FETCH_ASSIGN_INPUT_FOR_ASSIGNED = 'FETCH_ASSIGN_INPUT_FOR_ASSIGNED';
export const FETCH_PRODUCTION_SUB_PROCESS_FOR_ASSIGN_INPUT_TABLE = 'FETCH_PRODUCTION_SUB_PROCESS_FOR_ASSIGN_INPUT_TABLE';
export const ASSIGN_INPUT_TABLE_PENDING_MODAL_OPEN = 'ASSIGN_INPUT_TABLE_PENDING_MODAL_OPEN';
export const RESET_ASSIGN_INPUT_TABLE_STATE = 'RESET_ASSIGN_INPUT_TABLE_STATE';
export const LOADING = 'LOADING';

export const SELECTED_ASSIGN_INPUT_BUNDLE = 'SELECTED_ASSIGN_INPUT_BUNDLE';

/** Change Log
 * 26-Jan-2022(Iqbal): Add FETCH_ASSIGN_INPUT_TABLE_BY_QUERY, , FETCH_ASSIGN_INPUT_TABLE, FETCH_ASSIGN_INPUT_TABLE_BY_ID, FETCH_ASSIGN_INPUT_TABLE_BY_RANGE
 */
