/**
 * Title: Action Types for Critical Process
 * Description: Action Types for Critical Process
 * Author: Nasir Ahmed
 * Date: 10-January-2022
 * Modified: 10-January-2022
 **/

export const FETCH_CRITICAL_PROCESS = 'FETCH_CRITICAL_PROCESS';
export const TOGGLE_CRITICAL_PROCESS_SIDEBAR = 'TOGGLE_CRITICAL_PROCESS_SIDEBAR';
export const TOGGLE_CRITICAL_PROCESS_STATUS = 'TOGGLE_CRITICAL_PROCESS_STATUS';
export const FETCH_CRITICAL_PROCESS_BY_QUERY = 'FETCH_CRITICAL_PROCESS_BY_QUERY';
export const DELETE_CRITICAL_PROCESS = 'DELETE_CRITICAL_PROCESS';
export const FETCH_CRITICAL_PROCESS_BY_ID = 'FETCH_CRITICAL_PROCESS_BY_ID';
export const DELETE_CRITICAL_PROCESS_BY_RANGE = 'DELETE_CRITICAL_PROCESS_BY_RANGE';
export const FILL_PRODUCTION_PROCESS_DDL = 'FILL_PRODUCTION_PROCESS_DDL';
export const FILL_CRITICAL_PROCESS_DDL = 'FILL_CRITICAL_PROCESS_DDL';
export const RESET_CRITICAL_PROCESS_DDL = 'RESET_CRITICAL_PROCESS_DDL';
export const LOADING = 'LOADING';
