/*
     Title: Constant for PANEL_CHECK
     Description: Constant for PANEL_CHECK
     Author: Iqbal Hossain
     Date: 22-January-2022
     Modified: 22-January-2022
*/

export const FETCH_BUNDLE_BY_STATUS = 'FETCH_BUNDLE_BY_STATUS';

//----------------------
export const FETCH_UNCHECKED = 'FETCH_UNCHECKED';
export const FETCH_CHECKED = 'FETCH_CHECKED';
export const SET_CHECKED_BUNDLE = 'SET_CHECKED_BUNDLE';
export const SET_UNCHECKED_BUNDLE = 'SET_UNCHECKED_BUNDLE';
export const SET_UNCHECKED_REJECT_BUNDLE = 'SET_UNCHECKED_REJECT_BUNDLE';
export const TOGGLE_UNCHECKED = 'TOGGLE_UNCHECKED';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const TOGGLE_REJECT = 'TOGGLE_REJECT';
export const TOGGLE_UNCHECKED_ITEM_REJECT = 'TOGGLE_UNCHECKED_ITEM_REJECT';
export const TOGGLE_REJECT_MODAL = 'TOGGLE_REJECT_MODAL';
export const TOGGLE_UNCHECKED_REJECT_MODAL = 'TOGGLE_UNCHECKED_REJECT_MODAL';
export const TOGGLE_UNCHECKED_MODAL = 'TOGGLE_UNCHECKED_MODAL';
export const SHOW_BACK_DROP = 'SHOW_BACK_DROP';
export const LOADING = 'LOADING';

export const TOGGLE_UNCHECKED_BUNDLE_DAMAGE_STATUS = 'TOGGLE_UNCHECKED_BUNDLE_DAMAGE_STATUS';
export const TOGGLE_CHECKED_BUNDLE_DAMAGE_STATUS = 'TOGGLE_CHECKED_BUNDLE_DAMAGE_STATUS';

/** Change Log
 * 22-Jan-2022(Iqbal): Add TOGGLE_PANEL_CHECK_SIDEBAR, FETCH_PANEL_CHECK_BY_QUERY, ADD_PANEL_CHECK, DELETE_PANEL_CHECK, FETCH_PANEL_CHECK_BY_ID, UPDATE_PANEL_CHECK, DELETE_PANEL_CHECK_BY_RANGE
 */
