/*
      Title: Action Type
      Description: Action Type
      Author: Iqbal Hossain
      Date: 05-January-2022
      Modified: 05-January-2022
*/
export const FETCH_PRODUCTION_SUB_PROCESS_BY_PARENT_PROCESS_ID_AND_STATUS = 'FETCH_PRODUCTION_SUB_PROCESS_BY_PARENT_PROCESS_ID_AND_STATUS';
export const FETCH_OPERATOR_BY_PRODUCTION_PROCESS_ID = 'FETCH_OPERATOR_BY_PRODUCTION_PROCESS_ID';
export const FETCH_BUYER_BY_PRODUCTION_PROCESS_ID = 'FETCH_BUYER_BY_PRODUCTION_PROCESS_ID';
export const FETCH_STYLE_BY_PRODUCTION_PROCESS_ID_AND_BUYER_ID = 'FETCH_STYLE_BY_PRODUCTION_PROCESS_ID_AND_BUYER_ID';
export const FETCH_TRANSFER_STORE_ASSIGNED_QUANTITY = 'FETCH_TRANSFER_STORE_ASSIGNED_QUANTITY';
export const FETCH_FINISHING_BY_PRODUCTION_SUB_PROCESS_ID = 'FETCH_FINISHING_BY_PRODUCTION_SUB_PROCESS_ID';
export const FETCH_FINISHING_PASSED_BY_PRODUCTION_SUB_PROCESS_ID = 'FETCH_FINISHING_PASSED_BY_PRODUCTION_SUB_PROCESS_ID';
export const FETCH_FINISHING_DETAILS_BY_MASTER_ID = 'FETCH_FINISHING_DETAILS_BY_MASTER_ID';
export const RESET_FINISHING_STATE = 'RESET_FINISHING_STATE';
export const LOADING_FINISHING = 'LOADING_FINISHING';
