/*
     Title: Constant for EXTERNAL_PROCESS
     Description: Constant for EXTERNAL_PROCESS
     Author: Iqbal Hossain
     Date: 24-January-2022
     Modified: 24-January-2022
*/

export const FETCH_EXTERNAL_PROCESS = 'FETCH_EXTERNAL_PROCESS';
export const FETCH_EXTERNAL_PROCESS_BY_QUERY = 'FETCH_EXTERNAL_PROCESS_BY_QUERY';
export const FETCH_EXTERNAL_PROCESS_BY_ID = 'FETCH_EXTERNAL_PROCESS_BY_ID';
export const FETCH_EXTERNAL_PROCESS_BY_RANGE = 'FETCH_EXTERNAL_PROCESS_BY_RANGE';
export const FETCH_PRODUCTION_SUB_PROCESS_BY_STATUS_FOR_DDL = 'FETCH_PRODUCTION_SUB_PROCESS_BY_STATUS_FOR_DDL';
export const ON_PRODUCTION_PROCESS_CHANGE = 'ON_PRODUCTION_PROCESS_CHANGE';
export const FETCH_PARTIAL_BUNDLE_INFO_FOR_PENDING = 'FETCH_PARTIAL_BUNDLE_INFO_FOR_PENDING';
export const FETCH_PARTIAL_BUNDLE_INFO_FOR_SEND = 'FETCH_PARTIAL_BUNDLE_INFO_FOR_SEND';
export const TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_SEND = 'TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_SEND';
export const TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_PENDING = 'TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_PENDING';
export const TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_RECEIVED = 'TOGGLE_EXTERNAL_PROCESS_DETAILS_FOR_RECEIVED';
export const FETCH_PARTIAL_BUNDLE_INFO_FOR_RECEIVED = 'FETCH_PARTIAL_BUNDLE_INFO_FOR_RECEIVED';
export const FETCH_PARTIAL_BUNDLE_INFO_FOR_PASSED = 'FETCH_PARTIAL_BUNDLE_INFO_FOR_PASSED';
export const LOADING = 'LOADING';
export const TOGGLE_EXTERNAL_PROCESS_PENDING_MODAL = 'TOGGLE_EXTERNAL_PROCESS_PENDING_MODAL';
export const TOGGLE_EXTERNAL_PROCESS_SEND_MODAL = 'TOGGLE_EXTERNAL_PROCESS_SEND_MODAL';
export const TOGGLE_EXTERNAL_PROCESS_PASSED_MODAL = 'TOGGLE_EXTERNAL_PROCESS_PASSED_MODAL';
export const RESET_EXTERNAL_PROCESS_STATE = 'RESET_EXTERNAL_PROCESS_STATE';
export const TOGGLE_DAMAGE_BUNDLE_FROM_EXTERNAL_PROCESS = 'TOGGLE_DAMAGE_BUNDLE_FROM_EXTERNAL_PROCESS';

/** Change Log
 * 24-Jan-2022(Iqbal): Add FETCH_EXTERNAL_PROCESS_BY_QUERY, , FETCH_EXTERNAL_PROCESS, FETCH_EXTERNAL_PROCESS_BY_ID, FETCH_EXTERNAL_PROCESS_BY_RANGE
 */
