export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_AUTHENTICATE_USER = 'GET_AUTHENTICATE_USER';
export const GET_AUTHENTICATE_USER_PERMISSION = 'GET_AUTHENTICATE_USER_PERMISSION';

export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';

export const AUTH_TOKEN_STORE = 'AUTH_TOKEN_STORE';


export const FILE_PROGRESS = 'FILE_PROGRESS';

export const GET_PROGRESS = "GET_PROGRESS";
export const POST_PROGRESS = "POST_PROGRESS";
export const IS_OPEN_INSTANT_LOGIN_MODAL = "IS_OPEN_INSTANT_LOGIN_MODAL";

export const SESSION_DURATION = "SESSION_DURATION";


export const BIND_AUTH_NAVIGATION = "BIND_AUTH_NAVIGATION";


///For Data Progress and Loader
export const IS_DATA_LOADED_CM = "IS_DATA_LOADED_CM";
export const IS_DATA_PROGRESS_CM = "IS_DATA_PROGRESS_CM";
export const IS_DATA_SUBMIT_PROGRESS_CM = "IS_DATA_SUBMIT_PROGRESS_CM";

export const GET_ALL_STYLES_DROPDOWN_CM = 'GET_ALL_STYLES_DROPDOWN_CM';
