/*
     Title: Constant for SEWING_INSPECTION
     Description: Constant for SEWING_INSPECTION
     Author: Iqbal Hossain
     Date: 29-January-2022
     Modified: 29-January-2022
*/

export const FETCH_SEWING_INSPECTION = 'FETCH_SEWING_INSPECTION';
export const FETCH_TODAYS_SEWING_INSPECTION = 'FETCH_TODAYS_SEWING_INSPECTION';
export const FETCH_PREVIOUS_SEWING_INSPECTION = 'FETCH_PREVIOUS_SEWING_INSPECTION';
export const FETCH_SEWING_INSPECTION_BY_QUERY = 'FETCH_SEWING_INSPECTION_BY_QUERY';
export const FETCH_SEWING_INSPECTION_BY_ID = 'FETCH_SEWING_INSPECTION_BY_ID';
export const FETCH_SEWING_INSPECTION_BY_MASTER_ID = 'FETCH_SEWING_INSPECTION_BY_MASTER_ID';
export const RESET_SEWING_INSPECTION_DETAILS_DATA = 'RESET_SEWING_INSPECTION_DETAILS_DATA';
export const FETCH_LINE_DETAILS_FOR_SEWING_INSPECTION = 'FETCH_LINE_DETAILS_FOR_SEWING_INSPECTION';
export const LOADING = 'LOADING';
export const RESET_SEWING_INSPECTION_STATE = 'RESET_SEWING_INSPECTION_STATE';
export const FETCH_ASSIGN_TARGET_BY_LINE_ID_AND_ASSIGN_DATE = 'FETCH_ASSIGN_TARGET_BY_LINE_ID_AND_ASSIGN_DATE';
export const FILL_BUYER_DDL_BY_LINE_ID = 'FILL_BUYER_DDL_BY_LINE_ID';
export const FILL_STYLE_DDL_BY_LINE_AND_BUYER_ID = 'FILL_STYLE_DDL_BY_LINE_AND_BUYER_ID';

/** Change Log
 * 29-Jan-2022(Iqbal): Add TOGGLE_SEWING_INSPECTION_SIDEBAR, FETCH_SEWING_INSPECTION_BY_QUERY, FETCH_SEWING_INSPECTION_BY_ID,
 * 05-nov-2022(Ashraful): Added RESET_SEWING_INSPECTION_DETAILS_DATA
 */
