/*
     Title: Action Types for Style Wise Production Process Group
     Description: Action Types for Style Wise Production Process Group
     Author: Alamgir Kabir
     Date: 31-July-2022
     Modified: 31-July-2022
*/
export const LOADING = 'LOADING';
export const TOGGLE_STYLE_WISE_PRODUCTION_PROCESS_GROUP_SIDEBAR = 'TOGGLE_STYLE_WISE_PRODUCTION_PROCESS_GROUP_SIDEBAR';
export const FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_BY_QUERY = 'FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_BY_QUERY';
export const FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_BY_ID = 'FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_BY_ID';
export const FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_STATE = 'FETCH_STYLE_WISE_PRODUCTION_PROCESS_GROUP_STATE';
