/*
     Title: Constant for WASH
     Description: Constant for WASH
     Author: Iqbal Hossain
     Date: 12-February-2022
     Modified: 12-February-2022
*/

export const FETCH_WASH = 'FETCH_WASH';
export const LOADING_WASH_ITEM = 'LOADING_WASH_ITEM';
export const FETCH_WASH_SEND_ITEM_BY_PROCESS_ID = 'FETCH_WASH_SEND_ITEM_BY_PROCESS_ID';
export const FETCH_WASH_RECEIVE_ITEM_BY_PROCESS_ID = 'FETCH_WASH_RECEIVE_ITEM_BY_PROCESS_ID';
export const FETCH_WASH_PASSED_ITEM_BY_PROCESS_ID = 'FETCH_WASH_PASSED_ITEM_BY_PROCESS_ID';
export const FETCH_WASH_BY_QUERY = 'FETCH_WASH_BY_QUERY';
export const FETCH_WASH_BY_ID = 'FETCH_WASH_BY_ID';
export const FETCH_WASH_BY_MASTER_ID = 'FETCH_WASH_BY_MASTER_ID';
export const FETCH_WASH_RECEIVE_BY_MASTER_ID = 'FETCH_WASH_RECEIVE_BY_MASTER_ID';
export const FETCH_WASH_BY_RANGE = 'FETCH_WASH_BY_RANGE';
export const RESET_WASHING_STATE = 'RESET_WASHING_STATE';
export const FETCH_SIZE_INFO_BY_PROCESS_STYLE_COLOR_AND_LINE_ID = 'FETCH_SIZE_INFO_BY_PROCESS_STYLE_COLOR_AND_LINE_ID';
export const FETCH_NEXT_PRODUCTION_SUB_PROCESS_BY_CURRENT_PROCESS_AND_STYLE = 'FETCH_NEXT_PRODUCTION_SUB_PROCESS_BY_CURRENT_PROCESS_AND_STYLE';
export const FETCH_SIZE_INFO_BY_PROCESS_STYLE_COLOR_AND_LINE_ID_FOR_WASH_RECEIVE =
  'FETCH_SIZE_INFO_BY_PROCESS_STYLE_COLOR_AND_LINE_ID_FOR_WASH_RECEIVE';

/** Change Log
 * 12-Feb-2022(Iqbal): Add FETCH_WASH_BY_QUERY, FETCH_WASH, FETCH_WASH_BY_ID, FETCH_WASH_BY_RANGE
 */
