/*
     Title: Constant for LIne
     Description: Constant for LIne
     Author: Iqbal Hossain
     Date: 06-January-2022
     Modified: 06-January-2022
*/

export const FETCH_LINE = 'FETCH_LINE';
export const TOGGLE_LINE_SIDEBAR = 'TOGGLE_LINE_SIDEBAR';
export const FETCH_LINE_BY_QUERY = 'FETCH_LINE_BY_QUERY';
export const ADD_LINE = 'ADD_LINE';
export const DELETE_LINE = 'DELETE_LINE';
export const FETCH_LINE_BY_ID = 'FETCH_LINE_BY_ID';
export const FILL_LINE_BY_DDL = 'FILL_LINE_BY_DDL';
export const FILL_LINE_DDL_BY_ZONE_GROUP_ID = 'FILL_LINE_DDL_BY_ZONE_GROUP_ID';
export const UPDATE_LINE = 'UPDATE_LINE';
export const DELETE_LINE_BY_RANGE = 'DELETE_LINE_BY_RANGE';
export const LOADING = 'LOADING';
export const FETCH_CRITICAL_PROCESS_IN_LINES_BY_LINE_ID = 'FETCH_CRITICAL_PROCESS_IN_LINES_BY_LINE_ID';

export const OPEN_CRITICAL_PROCESS_MANAGE_MODAL = 'OPEN_CRITICAL_PROCESS_MANAGE_MODAL';
export const CLOSE_CRITICAL_PROCESS_MANAGE_MODAL = 'CLOSE_CRITICAL_PROCESS_MANAGE_MODAL';

export const RESET_CRITICAL_PROCESS_STATE = 'RESET_CRITICAL_PROCESS_STATE';

/** Change Log
 * 08-Jan-2022(Iqbal): Add TOGGLE_LINE_SIDEBAR, FETCH_LINE_BY_QUERY, ADD_LINE, DELETE_LINE, FETCH_LINE_BY_ID, UPDATE_LINE, DELETE_LINE_BY_RANGE
 * 24-Oct-2022(Ashraful Islam): Added OPEN_CRITICAL_PROCESS_MANAGE_MODAL, FETCH_CRITICAL_PROCESS_IN_LINES_BY_LINE_ID,
 */
